security:
    encoders:
        VulnerabilityChaser\FrontendBundle\Entity\Users: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_db:
            entity: { class: VulnerabilityChaser\FrontendBundle\Entity\Users, property:mail }

    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
