security:
    encoders:
        VulnerabilityChaser\FrontendBundle\Entity\Users: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_db:
            entity: { class: VulnerabilityChaser\FrontendBundle\Entity\Users, property:mail }

    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
            
                default_target_path: /login
                always_use_default_target_path: true
                use_referer:        true
                target_path_parameter: redirect_url
                failure_path: /login_failure
                
                # el usuario es redirigido aquí cuando necesita ingresar
                login_path:                     /login

                # si es 'true', reenvía al usuario al formulario de acceso en lugar de redirigirlo
                use_forward:                    true

                # aquí es dónde se presenta el formulario de acceso
                check_path:                     /login_check

                # por omisión, el método del formulario de acceso DEBE ser POST, no GET
                post_only:                      true

                # opciones para redirigir en ingreso satisfactorio (lee más adelante)
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false

                # opciones para redirigir en ingreso fallido (lee más adelante)
                failure_path:                   null
                failure_forward:                false

                # nombres de campo para el nombre de usuario y contraseña
                username_parameter:             _username
                password_parameter:             _password

                # opciones del elemento csrf
                csrf_parameter:                 _csrf_token
                intention:                      authenticate
                

            logout:
                path: /logout
                target: /
                
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
                
            security: true
            anonymous: true
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
