FrontendBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FrontendBundle:Default:index }
    
users:
    pattern: /user/users
    defaults: { _controller: FrontendBundle:Default:users }

upload:
    pattern: /upload
    defaults: { _controller: FrontendBundle:Import:upload }

login:
    pattern:  /user/login
    defaults: { _controller: FrontendBundle:Default:login }    

login2:
    pattern: /login
    defaults: { _controller: FrontendBundle:Security:login }
        
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout

vulnerabilities:
    pattern: /vulnerabilities
    defaults: { _controller: FrontendBundle:Vulnerabilities:show }

vulnerability:
    pattern: /vulnerability/{id}
    defaults: { _controller: FrontendBundle:Vulnerabilities:showVulnerability }
    
asset:
    pattern: /asset/{id}
    defaults: { _controller: FrontendBundle:Vulnerabilities:showAsset }

 