FrontendBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FrontendBundle:Default:index }
    
FrontendBundle_login:
    pattern:  /usuario/login
    defaults: { _controller: FrontendBundle:Default:login }    

users:
    pattern: /users
    defaults: { _controller: FrontendBundle:Default:users }

uploadScan:
    pattern: /upload
    defaults: { _controller: FrontendBundle:Default:upload }