FrontendBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FrontendBundle:Default:index }

users:
    pattern: /users
    defaults: { _controller: FrontendBundle:Default:users }

uploadScan:
    pattern: /upload
    defaults: { _controller: FrontendBundle:Default:upload }
